config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'

  namespace :admin do
    resources :users
  end

  namespace 'api', format: :json do
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    get '/logout', to: 'sessions#destroy'
    get '/signup', to: 'signup#new'
    post '/signup', to: 'signup#create'
    resources :tasks, except: :destroy do
      delete :destroy, on: :collection
    end
    patch 'tasks', to: 'tasks#update_tasks_order'
    resources :tags, only: %w[index create update destroy]
    resources :reports, only: %w[index] do
      # 単にparamsで取得できる情報があるかないかの違いでOK？
      # get 'period', to: 'reports#period'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
  has_one_attached :image

  # TODO: ユーザーが設定したカラム名に変換される
  enum status: { waiting: 0, working: 1, completed: 2, pending: 3 }

  validates :name, presence: true, length: { maximum: 30 }
  validate :validate_name_not_including_comma

  belongs_to :user
  has_many :task_tags, dependent: :destroy
  has_many :tags, through: :task_tags
  has_many :working_times, dependent: :destroy
  has_one :order
  delegate :position, to: :order

  paginates_per 20

  scope :recent, -> { order(created_at: :desc) }

  def self.ransackable_attributes(_auth_object = nil)
    %w[name created_at]
  end

  def self.ransackable_associations(_auth_object = nil)
    []
  end

  def self.csv_attributes
    %w[name description created_at updated_at]
  end

  def self.generate_csv
    CSV.generate(headers: true) do |csv|
      csv << csv_attributes
      all.each do |task|
        csv << csv_attributes.map { |attr| task.send(attr) }
      end
    end
  end

  # def self.import(files)
  #   files.each do |file|
  #     CSV.foreach(file.path, headers: true) do |row|
  #       # importがTaskから呼ばれている場合に、Task.newと同義となる（今回はcurrent_user.tasksから呼ばれているので、タスクにユーザを紐づけてからnewする）
  #       # headerがないファイルだと、rowの各要素に対して、キーが割り当てられない
  #       task = new
  #       task.attributes = row.to_hash.slice(*csv_attributes)
  #       task.save!
  #     end
  #   end
  # end

  private

  def validate_name_not_including_comma
    errors.add(:name, 'にカンマを含めることは出来ません！') if name&.include?(',')
  end
end

app/controllers/api/tasks_controller.rb
class Api::TasksController < ApplicationController
  before_action :set_task, only: %w[show update]
  # before_action :set_tasks_and_working_times, only: %w[index]
  before_action :set_useable_tags, only: %w[index show]

  def index
    # FIXME: boards.last部分は将来的に、表示中のboardのみになるのでそれまでは決め打ちでlastにしておく
    set_datas
  end

  def show
    @working_time = WorkingTime.total_working_time @task.id
    respond_to do |format|
      format.json
    end
  end

  def create
    # TODO: finisied_atの文字列をTimeWithZoneに変換しているのはどこで行われているか調査
    # TODO: 恐らくorderに関するパラメータも受け取るため、そのパラメータをもとにorderの生成を行う
    @task = current_user.tasks.new(task_params)

    if @task.save
      render :show
    else
      # TODO: エラーメッセージ
      render :index
    end
  end

  # rubocop:disable Metrics/MethodLength, Metrics/AbcSize
  # FIXME: 複数のリソースに対するupdateを行なってしまっていて分かりにくいので、分解するかモデルに処理させる
  def update
    # update! + working_timeに関する更新はtransactionで囲む
    @task.update!(task_params)
    times = params[:task][:times]

    render :show and return unless times

    update_target = WorkingTime.find_by(task_id: @task.id, recorded_at: Date.parse(params[:task][:times][:start_at]))
    if update_target
      update_target.times << times
      update_target.save!
    else
      WorkingTime.new(
        task_id: @task.id,
        times: [times],
        # TODO: end_atが日を跨いだ場合の対応
        recorded_at: Date.parse(params[:task][:times][:start_at])
      ).save!
    end
    render :show
  end
  # rubocop:enable Metrics/MethodLength, Metrics/AbcSize

  def destroy
    Task.where(id: params[:id]).destroy_all
    render json: { status: 200 }
  end

  # TODO: ユーザー入力値についてのバリデーション等の対策
  # 期待するリクエストパラメータ
  # { tasks: [], list_id: num }
  # TODO: 紐づくlist.idがリクエストパラメータのものと異なる場合、list.idの更新を行う
  def update_tasks_order
    # 使用ケース
    #   リスト内のカードの移動、リスト間でのカードの移動、タスク追加、タスク削除
    Order.update_order(order_params)
    # set_tasks_and_working_times
    set_datas
    render :index
  end

  private

  def set_datas
    lists = current_user.boards.last.lists
    tasks = current_user.tasks.eager_load(:order, :tags)
    @datas = lists.reduce([]) do |array, list|
      array.push({
                   list_id: list.id,
                   list_name: list.name,
                   tasks: tasks.where(order: { list_id: list.id })
                    .sort_by(&:position)
                 })
    end
  end

  # XXX: 中間テーブルに関する情報を毎回ここのparams内で取得するのが面倒
  def task_params
    params.require(:task).permit(:name, :description, :image, :finished_at, :times, :status, tag_ids: [])
  end

  def set_task
    # TODO: params[:task][:id]のパターンが必要かについて
    @task = current_user.tasks.find(params[:id]) || current_user.tasks.find(params[:task][:id])
  end

  def set_tasks_and_working_times
    # @q = current_user.tasks.ransack(params[:q])
    # @tasks = @q.result(distinct: true).page(params[:page]).order('created_at DESC')
    @working_times = WorkingTime.total_working_time_per_task
  end

  def set_useable_tags
    @tags = current_user.tags
  end

  def order_params
    # TODO: リスト内の順番を受け取る方向性について（positionパラメータを必要とするか、task_idの配列内の順番で考えるか）
    params.require(:order_params).map { |param| param.permit(:position, :task_id, :list_id).to_h }
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %w[show update destroy]
  before_action :set_tasks, only: %w[index]

  def index
    # CSVでエクスポートしたい、とかになったらformat.csvを復活させる
    # respond_to do |format|
    #   format.json { render json: @tasks }
    #   format.html
    #   format.csv { send_data @tasks.generate_csv, filename: "tasks-#{Time.zone.now.strftime('%Y%m%d%S')}.csv" }
    # end
  end

  def show; end

  def new
    # 保存に失敗した場合にrenderされるが、newアクションは経由しない
    @task = Task.new
  end

  def create
    # 保存失敗時、@taskの情報（ユーザ入力情報）を保持しておく
    # redirect_toの際に@taskを渡すと、ID値を含んだURLが返ってくる
    @task = current_user.tasks.new(task_params)

    # 戻るボタンが押されたら新規作成画面に戻る
    if params[:back].present?
      render :new
      return
    end

    if @task.save
      TaskMailer.creation_email(@task).deliver_now
      redirect_to @task, notice: "タスク「#{@task.name}」を登録しました！"
    else
      render :new
    end
  end

  def update
    @task.update!(task_params)
    redirect_to tasks_path, notice: "タスク 「#{@task.name}を更新しました」"
  end

  def destroy
    @task.destroy
  end

  # 確認画面表示
  def confirm_new
    @task = current_user.tasks.new(task_params)
    render :new unless @task.valid?
  end

  def import
    if params[:files].nil?
      set_tasks
      redirect_to tasks_path, flash: { danger: 'ファイルを選択してください' }
      return
    end
    current_user.tasks.import(params[:files])
    redirect_to tasks_url, notice: 'タスクを追加しました'
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :image, :finished_at, :elapsed_time)
  end

  def set_task
    @task = current_user.tasks.find_by(id: params[:id]) || current_user.tasks.find_by(id: params[:task][:id])
  end

  # ログインユーザに紐づくタスクのみ取得できるようにする(=tasks.where(id: current_user.id))
  def set_tasks
    @q = current_user.tasks.ransack(params[:q])
    @tasks = @q.result(distinct: true).page(params[:page]).order('created_at DESC')
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.slim
/ 右配置のためのクラス内に、nav-linkを入れる
.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'

/ ここのエラーメッセージの表示をモダンにしたい
- if task.errors.present?
  u1#error_explanation
    - task.errors.full_messages.each do |message|
      li = message

/ local: trueとすることで、Ajax通信を行うようにする
= form_with model: task, local: true do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'task_name'
  .form-group
    = f.label :tag_list
    = f.text_area :tag_list, rows: 5, value: @task.tag_list.join(','), class: 'form-control', id: 'task_description'
  .form-group
    = f.label :description
    = f.text_area :description, rows: 5, class: 'form-control', id: 'task_description'
  .form-group
    = f.label :finished_at
    = f.date_field :finished_at, class: 'form-control input-sm', id: 'task_finished_at', style: 'width: 13em'
  .form-group
    = f.label :image
    = f.file_field :image, class: 'form-control'
  = f.submit nil, class: 'btn btn-primary'

app/views/tasks/index.html.slim
/ = javascript_pack_tag 'hello_react'
h1 タスク一覧

= search_form_for @q, class: 'mb-5' do |f|
  .form-group.row
    = f.label :name_cont, '名称', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.search_field :name_cont, class: 'form-control'
  .form-group.row
    = f.label :created_at_gteq, '登録日付', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.search_field :created_at_gteq, class: 'form-control'
  .form-group
    = f.submit class: 'btn btn-outline-primary'

= link_to '新規登録', new_task_path, class: 'btn btn-primary mb-3'

.mb-3
  = paginate @tasks
  = page_entries_info @tasks

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th = sort_link(@q, :name, default_order: :desc)
      th = Task.human_attribute_name(:description)
      th = Task.human_attribute_name(:finished_at)
      th = Task.human_attribute_name(:elapsed_time)
    tbody
      - @tasks.each do |task|
        / 行クリックで編集ページに遷移
        / tr内にonclickを仕込む方法
        tr id="task-#{task.id}" onclick="window.location.href='#{task_url(task)}'"
          td = task.name
          td = task.description
          td = l(task.finished_at)
          td id="timer-#{task.id}"
            = task.elapsed_time&.strftime("%H:%M:%S") || '00:00:00'
          td
            = icon("fas", "play", id: "#{task.id}")
          / TODO:編集は行を押した際に遷移
          / TODO:タスクの削除は行の右端のオプションボタンで選択
          / td
          /   = link_to '編集', edit_task_path(task), class: 'btn btn-primary mr-3'
          /   = link_to '削除', task, method: :delete, remote: true, data: { confirm: "タスク「#{task.name}」を削除しますか？" },class: 'btn btn-danger delete'

= link_to 'エクスポート', tasks_path(format: :csv), class: 'btn btn-primary mb-3'

= form_tag import_tasks_path, multipart: true, class: 'mb-3' do
  = file_field_tag 'files[]', multiple: true
  = submit_tag "インポート", class: 'btn btn-primary'

app/views/tasks/show.html.slim
h1 タスクの詳細

.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'
table.table.table-hover
  tbody
    tr
      / モデル名とモデルの属性の翻訳を使うことができる
      / thで太字中央揃え、tdで細字左揃え
      th = Task.human_attribute_name(:id)
      td = @task.id
    tr
      th = Task.human_attribute_name(:name)
      td = @task.name
    tr
      th = Task.human_attribute_name(:tag)
      td = @task.tag_list
    tr
      th = Task.human_attribute_name(:description)
      td = auto_link(simple_format(h(@task.description), {}, sanitize: false, wrapper_tag: "div"))
    tr
      th = Task.human_attribute_name(:image)
      td = image_tag @task.image if @task.image.attached?
    tr
      th = Task.human_attribute_name(:finished_at)
      td = l(@task.finished_at, format: :default)
    tr
      th = Task.human_attribute_name(:created_at)
      td = l(@task.created_at, format: :long)
    tr
      th = Task.human_attribute_name(:updated_at)
      td = l(@task.updated_at, format: :long)

= link_to '編集', edit_task_path, class: 'btn btn-primary mr-3'
= link_to '削除', task_path, method: :delete, data: { confirm: "タスク「#{@task.name}」を削除しますか？" },class: 'btn btn-danger'
    