config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'

  namespace :admin do
    resources :users
  end

  namespace 'api', format: :json do
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    get '/logout', to: 'sessions#destroy'
    get '/signup', to: 'signup#new'
    post '/signup', to: 'signup#create'
    resources :tasks, except: :destroy do
      delete :destroy, on: :collection
    end
    patch 'tasks', to: 'tasks#update_tasks_order'
    resources :tags, only: %w[index create update destroy]
    resources :reports, only: %w[index] do
      # 単にparamsで取得できる情報があるかないかの違いでOK？
      # get 'period', to: 'reports#period'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # userテーブルにpasswordを保存する時に、暗号化してくれる
  # authenticate（ログイン認証用）メソッドが使えるようになる
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :boards, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :tags, dependent: :destroy
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :login_required

  def index
    @users = User.all.order(created_at: 'DESC')
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: "ユーザー「#{@user.name}」を登録しました！"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: "ユーザー「#{@user.name}」を更新しました"
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url, notice: "ユーザー「#{@user.name}」を削除しました"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  end

  # 作成されたユーザかの確認を行う
  # def require_admin
  #   redirect_to root_path unless current_user.admin?
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.slim
.nav.justify-content-end
  = link_to '一覧', admin_users_path, class: 'nav-link'

/ ここのエラーメッセージの表示をモダンにしたい
- if user.errors.present?
  u1#error_explanation
    - user.errors.full_messages.each do |message|
      li = message

= form_with model: [:admin, user], local: true do |f|
  .form-group
    = f.label :name, '名前'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, 'メールアドレス'
    = f.text_field :email, class: 'form-control'
  .form-check
    = f.label :admin, class: 'form-check-label' do
      = f.check_box :admin, class: 'form-check-input'
      | 管理者権限
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation, 'パスワード（確認）'
    = f.password_field :password_confirmation, class: 'form-control'
  = f.submit '登録する', class: 'btn btn-primary'
  

app/views/admin/users/edit.html.slim
h1 ユーザー編集

= render partial: 'form', locals: { user: @user }

app/views/admin/users/index.html.slim
h1 ユーザー一覧

= link_to '新規登録', new_admin_user_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th = User.human_attribute_name(:name)
      th = User.human_attribute_name(:email)
      th = User.human_attribute_name(:admin)
      th = User.human_attribute_name(:created_at)
      th = User.human_attribute_name(:updated_at)
      th
    tbody
      - @users.each do |user|
        tr
          td = link_to user.name, [:admin, user]
          td = user.email
          td = user.admin? ? 'あり' : 'なし'
          td = l(user.created_at, format: :long)
          td = l(user.updated_at, format: :long)
          td
            = link_to '編集', edit_admin_user_path(user), class: 'btn btn-primary mr-3'
            = link_to '削除', [:admin, user], method: :delete, data: { confirm: "ユーザ「#{user.name}」を削除しますか？" },class: 'btn btn-danger'

app/views/admin/users/new.html.slim
h1 ユーザー登録

= render partial: 'form', locals: { user: @user }

app/views/admin/users/show.html.slim
h1 ユーザー詳細

.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'
table.table.table-hover
  tbody
    tr
      / モデル名とモデルの属性の翻訳を使うことができる
      / thで太字中央揃え、tdで細字左揃え
      th = User.human_attribute_name(:name)
      td = @user.name
    tr
      th = User.human_attribute_name(:email)
      td = @user.email
    tr
      th = User.human_attribute_name(:admin)
      td = @user.admin? ? '権限あり' : '権限なし'
    tr
      th = User.human_attribute_name(:created_at)
      td = l(@user.created_at, format: :long)
    tr
      th = User.human_attribute_name(:updated_at)
      td = l(@user.updated_at, format: :long)

= link_to '編集', edit_admin_user_path, class: 'btn btn-primary mr-3'
= link_to '削除', [:admin, @user], method: :delete, data: { confirm: "ユーザー「#{@user.name}」を削除しますか？" }, class: 'btn btn-danger'