config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'

  namespace :admin do
    resources :users
  end

  namespace 'api', format: :json do
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    get '/logout', to: 'sessions#destroy'
    get '/signup', to: 'signup#new'
    post '/signup', to: 'signup#create'
    resources :tasks, except: :destroy do
      delete :destroy, on: :collection
    end
    patch 'tasks', to: 'tasks#update_tasks_order'
    resources :tags, only: %w[index create update destroy]
    resources :reports, only: %w[index] do
      # 単にparamsで取得できる情報があるかないかの違いでOK？
      # get 'period', to: 'reports#period'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Taskleaf
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      .navbar-brand Taskleaf
      = current_user.name unless current_user.nil?

      ul.navbar-nav.ml-auto
        - if current_user
          li.nav-item = link_to 'タスク一覧', tasks_path, class:'nav-link'
          - if current_user.admin?
            li.nav-item = link_to 'ユーザ一覧', admin_users_path, class:'nav-link'
          li.nav-item = link_to 'ログアウト', logout_path, class:'nav-link'
        - else
          li.nav-item= link_to 'ログイン', login_path, class:'nav-link'
    .container
      - if flash[:notice].present?
        .alert.alert-success = flash[:notice]
      - if flash[:danger].present?
        .alert.alert-danger = flash[:danger]
      = yield